---
info:
  title: Datahub Actions
  description: DataHub Actions is a framework for responding to changes to your DataHub
    Metadata Graph in real time.
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/datahub-actions
  x-cortex-tag: datahub-actions
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: platform-analytics
  x-cortex-groups:
  - exposure:internal-ship
openapi: 3.0.1
servers:
- url: "/"
